"""Module containing the definition of a Directed Graph Extension of networkx.DiGraph."""

from collections import defaultdict
from collections.abc import Iterable, Sequence
from copy import deepcopy
from itertools import chain
from typing import Any, Optional

import networkx as nx
from networkx import NetworkXNoCycle, NetworkXUnfeasible, find_cycle
from typing_extensions import Self

from tawazi.config import Config
from tawazi.consts import Identifier, Tag
from tawazi.errors import TawaziUsageError
from tawazi.node import ExecNode, UsageExecNode


class DiGraphEx(nx.DiGraph):
    """Extends the DiGraph with some methods."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        # Access to nodes data is very slow, using dict is faster
        self.tag: dict[Identifier, Optional[list[Tag]]] = defaultdict(lambda: None)
        self.debug: dict[Identifier, bool] = defaultdict(lambda: False)
        self.setup: dict[Identifier, bool] = defaultdict(lambda: False)
        self.compound_priority: dict[Identifier, int] = defaultdict(lambda: 0)

    @classmethod
    def from_exec_nodes(
        cls, input_nodes: list[UsageExecNode], exec_nodes: dict[Identifier, ExecNode]
    ) -> Self:
        """Build a DigraphEx from exec nodes.

        Args:
            input_nodes: nodes that are the inputs of the graph
            exec_nodes: the graph nodes

        Returns:
            the DigraphEx object
        """
        pass

    def add_exec_node(self, xn: ExecNode) -> None:
        """Add an ExecNode and its dependencies to the graph."""
        pass

    def make_subgraph(
        self,
        target_nodes: Optional[list[str]] = None,
        exclude_nodes: Optional[list[str]] = None,
        root_nodes: Optional[list[str]] = None,
    ) -> Self:
        """Builds the DigraphEx, with potential graph pruning.

        Args:
            target_nodes: nodes that we want to run and their dependencies
            exclude_nodes: nodes that should be excluded from the graph
            root_nodes: base ancestor nodes from which to start graph resolution

        Returns:
            Base Graph that will be used for the computations
        """
        pass

    @property
    def root_nodes(self) -> set[Identifier]:
        """Safely gets the root nodes.

        Returns:
            List of root nodes
        """
        pass

    def remove_root_node(self, root_node: Identifier) -> set[Identifier]:
        """Removes a root node and returns all the new root nodes generated by this modification to the DAG."""
        pass

    def remove_any_root_node(self) -> Identifier:
        """Removes any root node and returns the removed root node."""
        pass

    @property
    def leaf_nodes(self) -> list[Identifier]:
        """Safely get the leaf nodes.

        Returns:
            List of leaf nodes
        """
        pass

    @property
    def debug_nodes(self) -> list[Identifier]:
        """Get the debug nodes.

        Returns:
            the debug nodes
        """
        pass

    @property
    def setup_nodes(self) -> list[Identifier]:
        """Get the setup nodes.

        Returns:
            the setup nodes
        """
        pass

    @property
    def tags(self) -> set[str]:
        """Get all the tags available for the graph.

        Returns:
            A set of tags
        """
        pass

    @property
    def topologically_sorted(self) -> list[Identifier]:
        """Makes the simple topological sort of the graph nodes.

        Returns:
            List of nodes of the graph listed in topological order
        """
        pass

    def get_tagged_nodes(self, tag: Tag) -> list[str]:
        """Get nodes with a certain tag.

        Args:
            tag: the tag identifier

        Returns:
            a list of nodes
        """
        pass

    def single_node_successors(self, node_id: Identifier) -> list[Identifier]:
        """Get all the successors of a node with a depth first search.

        Args:
            node_id: the node acting as the root of the search

        Returns:
            list of the node's successors
        """
        pass

    def multiple_nodes_successors(self, nodes_ids: Sequence[Identifier]) -> set[Identifier]:
        """Get the successors of all nodes in the iterable.

        Args:
            nodes_ids: nodes of which we want successors

        Returns:
            a set of all the sucessors
        """
        pass

    def remove_recursively(self, root_node: Identifier, remove_root_node: bool = True) -> None:
        """Recursively removes all the nodes that depend on the provided.

        Args:
            root_node (Identifier): the root node
            remove_root_node (bool, optional): whether to remove the root node or not. Defaults to True.
        """
        pass

    def include_debug_nodes(self, leaves_ids: list[Identifier]) -> list[Identifier]:
        """Get debug nodes that are runnable with provided nodes as direct roots.

        For example:
        A
        |
        B
        | \
        D E

        if D is not a debug ExecNode and E is a debug ExecNode.
        If the subgraph whose leaf ExecNode D is executed,
        E should also be included in the execution because it can be executed (debug node whose inputs are provided)
        Hence we should extend the subgraph containing only D to also contain E

        Args:
            leaves_ids: the leaves ids of the subgraph

        Returns:
            the leaves ids of the new extended subgraph that contains more debug ExecNodes
        """
        pass

    def extend_graph_with_debug_nodes(self, original_graph: Self, cfg: Config) -> Self:
        """Add or remove debug nodes depending on the configuration.

        Args:
            original_graph: the graph containing a broader set of nodes
            cfg: the tawazi configuration

        Returns:
            the correct subgraph
        """
        pass

    def minimal_induced_subgraph(self, nodes: list[Identifier]) -> Self:
        """Get the minimal induced subgraph containing the provided nodes.

        The generated subgraph contains the provided nodes as leaf nodes.
        For example:
        graph =
        "
        A
        | \
        B  C
        |  |\
        D  E F
        "
        subgraph_leaves(D, C, E) ->
        "
        A
        | \
        B  C
        |  |
        D  E
        "
        C is not a node that can be made into leaf nodes

        Args:
            nodes: the list of nodes to be executed

        Returns:
            the induced subgraph over the original graph with the provided nodes:

        Raises:
            ValueError: if the provided nodes are not in the graph
        """
        pass

    def ancestors_of_iter(self, nodes: Iterable[Identifier]) -> set[Identifier]:
        """Returns the ancestors of the provided nodes.

        Args:
            nodes (Set[Identifier]): The nodes to find the ancestors of

        Returns:
            Set[Identifier]: The ancestors of the provided nodes
        """
        pass

    def assign_compound_priority(self) -> None:
        """Assigns a compound priority to all nodes in the graph.

        The compound priority is the sum of the priorities of all children recursively.
        """
        pass
